name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.11]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        python -m pip install -r requirements.txt  # Załóżmy, że masz plik z zależnościami

    - name: Display Python Version
      run: python --version

    - name: Run flake8
      run: |
        flake8

    - name: Run Unit Tests
      run: |
        python -m unittest discover -p '*_test.py'
